export const CustomTheme = { 
    Default:  {
        Primary: '#38A6DE',
        PrimaryColor_2: '#18508D',
        PrimaryColor_3: '#64C4F5',
        PrimaryColor_4: '#E2F6FF',
        PrimaryColor_5: '#9FA0A5',
        PrimaryColor_6: '#DFDFDF',
        Secondary: '#FFFFFF',
        SecondaryColor_2: '#000000',
    },
    Red:  {
        Primary: '#f10',
        PrimaryColor_2: '#18508D',
        PrimaryColor_3: '#64C4F5',
        PrimaryColor_4: '#E2F6FF',
        PrimaryColor_5: '#9FA0A5',
        PrimaryColor_6: '#DFDFDF',
        Secondary: '#FFFFFF',
        SecondaryColor_2: '#000000',
    },
    Green:  {
        Primary: 'green',
        PrimaryColor_2: '#18508D',
        PrimaryColor_3: '#64C4F5',
        PrimaryColor_4: '#E2F6FF',
        PrimaryColor_5: '#9FA0A5',
        PrimaryColor_6: '#DFDFDF',
        Secondary: '#FFFFFF',
        SecondaryColor_2: '#000000',
    },
}